root = "." 
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app/engine cmd/main.go"
bin = "tmp/app"

full_bin = "./tmp/app/engine http"
log = "air_errors.log"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp"]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true